# Generated by Django 5.1 on 2025-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
