# Generated by Django 5.0.1 on 2025-03-31 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_min_stock_level"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary supplier",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplier",
            ),
        ),
    ]
