# Generated by Django 5.0.1 on 2025-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0002_remove_product_address_remove_product_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="discontinued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="lead_time_days",
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_point",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(default="unit", max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
