# Generated by Django 5.0.1 on 2025-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="supplier",
            name="supplier_code",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
    ]
