# Generated by Django 5.1 on 2025-02-13 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('customer_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=50, null=True, unique=True)),
                ('weather_condition', models.CharField(blank=True, help_text='Weather condition on transaction date', max_length=50, null=True)),
                ('is_holiday', models.BooleanField(default=False, help_text='Is the transaction date a holiday?')),
                ('is_promotion', models.BooleanField(default=False, help_text='Was there a promotion on the transaction date?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('supplier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
