# Generated by Django 5.0.1 on 2025-02-11 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_supplier_notes_supplier_payment_terms_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
